# Generated by Django 3.0.3 on 2020-02-25 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clueID', models.AutoField(primary_key=True, serialize=False)),
                ('clueText', models.CharField(max_length=255)),
                ('imageFilePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('clueID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Clue')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('taskText', models.CharField(max_length=255)),
                ('taskAnswer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20)),
                ('teamMembers', models.IntegerField()),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteLocationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Location')),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Route')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Task'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Team')),
            ],
        ),
    ]
