# Generated by Django 3.0.3 on 2020-02-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='location1',
        ),
        migrations.CreateModel(
            name='RouteLocationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.Location')),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.Route')),
            ],
        ),
    ]
