# Generated by Django 3.0.3 on 2020-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teamID',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
