# Generated by Django 3.0.3 on 2020-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_auto_20200226_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='clueID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
