# Generated by Django 3.0.3 on 2020-02-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_auto_20200225_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20)),
                ('teamMembers', models.IntegerField()),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Route')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teamID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Team'),
            preserve_default=False,
        ),
    ]
