# Generated by Django 3.0.3 on 2020-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0003_auto_20200225_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('modelID', models.AutoField(primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=20)),
            ],
        ),
    ]
