# Generated by Django 3.0.3 on 2020-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0003_auto_20200226_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamID',
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
