# Generated by Django 3.0.3 on 2020-02-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testmodel',
        ),
    ]
