# Generated by Django 3.0.3 on 2020-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='routeName',
            field=models.CharField(default='NoRoute', max_length=20),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clueID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clueText',
            field=models.CharField(default='NoClue', max_length=255),
        ),
        migrations.AlterField(
            model_name='clue',
            name='imageFilePath',
            field=models.CharField(default='NoPath', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='NoAddress', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='NoName', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskAnswer',
            field=models.CharField(default='NoAnswer', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskText',
            field=models.CharField(default='NoTask', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
