# Generated by Django 3.0.3 on 2020-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_auto_20200226_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=20),
        ),
    ]
