# Generated by Django 3.0.3 on 2020-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0007_auto_20200225_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='NoDescription', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='NoAddress', max_length=255),
        ),
    ]
