# Generated by Django 3.0.3 on 2020-02-25 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0008_auto_20200225_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routelocationmapping',
            name='locationID',
        ),
        migrations.RemoveField(
            model_name='routelocationmapping',
            name='routeID',
        ),
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='routeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='treasurehunt.Route'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='RouteLocationMapping',
        ),
    ]
